"""remove booking id from payment

Revision ID: 13ebb538bbd1
Revises: 25853ed76924
Create Date: 2024-09-17 21:28:14.205512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13ebb538bbd1'
down_revision = '25853ed76924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payer_email',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_constraint('fk_payment_booking', type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key('fk_payment_booking', 'bookings', ['booking_id'], ['id'])
        batch_op.alter_column('payer_email',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
