"""add relationship user-motel

Revision ID: 1bbd7e63ee60
Revises: d0bd6e49a7c4
Create Date: 2024-08-31 20:10:51.796127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbd7e63ee60'
down_revision = 'd0bd6e49a7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key('fk_user_motel', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_motel', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
