"""add payer_email to db

Revision ID: 25853ed76924
Revises: b53468ddf59a
Create Date: 2024-09-17 12:10:16.724265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25853ed76924'
down_revision = 'b53468ddf59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_email', sa.String(length=36), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('payer_email')

    # ### end Alembic commands ###
