"""add motels and rooms tables

Revision ID: 6efc8c0806ec
Revises: c09698e193c1
Create Date: 2024-08-13 20:01:11.466258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efc8c0806ec'
down_revision = 'c09698e193c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('max_room', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('water_price', sa.Float(), nullable=False),
    sa.Column('electric_price', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(length=256), nullable=True),
    sa.Column('motel_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['motel_id'], ['motels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('motels')
    # ### end Alembic commands ###
