"""add file field to motel

Revision ID: d0bd6e49a7c4
Revises: 4ca401789343
Create Date: 2024-08-31 19:05:17.757939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bd6e49a7c4'
down_revision = '4ca401789343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motels', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
