"""add new foreign key

Revision ID: d0c56dd8992d
Revises: 6efc8c0806ec
Create Date: 2024-08-14 04:44:48.321037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c56dd8992d'
down_revision = '6efc8c0806ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key("fk_room_post", 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint("fk_room_post", type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
